Module 2 Task 1
js-tasks-ru/jsbasic-20230428_anastasiya-nechaeva pull request #3
Opened 2023-05-07 13:51 UTC by AnastasiaNech

2023-05-07 13:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-07 14:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-09 15:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-10 10:11 UTC, SinimaWath requested changes

2023-05-10 10:11 UTC, SinimaWath commented on 2-module/1-task/index.js
> +   return sum == null ? 0 : sum;
В твоем случае, у тебя sum, никогда не может быть равен null, поэтому тут проверка не нужна: `return sum;`

2023-05-12 15:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-12 15:28 UTC, SinimaWath requested changes

2023-05-12 15:28 UTC, SinimaWath commented on 3-module/5-task/index.js
>  }
Нет необходимости в временной переменной
```
return {
     min: Math.min(...a),
    max: Math.max(...a)
};
```

2023-05-12 15:28 UTC, SinimaWath commented on 3-module/4-task/index.js
> +    .join('\n').toString();
`.toString()`- здесь лишняя, так как join('\n') - и так возвращает строку

2023-05-12 15:57 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-13 16:34 UTC, SinimaWath approved these changes

2023-05-13 16:35 UTC, merged